export default {
    SET_INIT_FEE: 'SET_INIT_FEE',
    SET_INTEREST_RATE: 'SET_INTEREST_RATE',
    SET_LOAN_TERM_FROM_MONTH: 'SET_LOAN_TERM_FROM_MONTH',
    SET_LOAN_TERM_FROM_YEAR: 'SET_LOAN_TERM_FROM_YEAR',
    SET_PERCENT_ANCHOR: 'SET_PERCENT_ANCHOR',
    SET_PRICE: 'SET_PRICE',
}
