const SET_INIT_FEE = 'SET_INIT_FEE';
const SET_INTEREST_RATE = 'SET_INTEREST_RATE';
const SET_LOAN_TERM_FROM_MONTH = 'SET_LOAN_TERM_FROM_MONTH';
const SET_LOAN_TERM_FROM_YEAR = 'SET_LOAN_TERM_FROM_YEAR';
const SET_PERCENT_ANCHOR = 'SET_PERCENT_ANCHOR';
const SET_PRICE = 'SET_PRICE';
